/*
 * TD8 - tinyllm: run the micro-LLM on one request and show what the OS sees.
 *   ./tinyllm [-m weights] [-v] "lista los archivos de docs"
 *   -v   print, for every generated byte, the 3 most likely candidates, and the costs:
 *        mapped weights, KV cache, tokens per second, page faults (getrusage)
 */
#include <stdio.h>
#include <stdlib.h>
#include <sys/resource.h>
#include <time.h>
#include <unistd.h>

#include "tinyllm.h"
#include "utils.h"

static void show_byte(int c)
{
    if (c == '\n') printf("\\n");
    else if (c < 32 || c > 126) printf("\\x%02x", c);
    else printf("%c", c);
}

static void trace(int step, const int top[3], const float prob[3], void *arg)
{
    (void)arg;
    printf("  step %2d:", step);
    for (int k = 0; k < 3; k++) {
        printf("  '");
        show_byte(top[k]);
        printf("' %5.1f%%", 100.0f * prob[k]);
    }
    printf("\n");
}

static double now(void)
{
    struct timespec t;
    clock_gettime(CLOCK_MONOTONIC, &t);
    return (double)t.tv_sec + (double)t.tv_nsec / 1e9;
}

int main(int argc, char *argv[])
{
    const char *weights = "weights/tinyllm.bin";
    int verbose = 0, opt;

    while ((opt = getopt(argc, argv, "m:v")) != -1) {
        if (opt == 'm') weights = optarg;
        else if (opt == 'v') verbose = 1;
        else {
            fprintf(stderr, "usage: %s [-m weights] [-v] \"request\"\n", argv[0]);
            return EXIT_FAILURE;
        }
    }
    if (optind >= argc) {
        fprintf(stderr, "usage: %s [-m weights] [-v] \"request\"\n", argv[0]);
        return EXIT_FAILURE;
    }

    struct rusage r0, r1, r2;
    getrusage(RUSAGE_SELF, &r0);
    double t0 = now();
    tl_model m;
    exit_if(tl_load(&m, weights) == -1, weights);
    getrusage(RUSAGE_SELF, &r1);
    double t1 = now();

    char out[256];
    int steps = tl_generate(&m, argv[optind], out, sizeof out, verbose ? trace : NULL, NULL);
    exit_if(steps < 0, "request too long for the context");
    double t2 = now();
    getrusage(RUSAGE_SELF, &r2);

    printf("%s\n", out);
    if (verbose) {
        int prompt_len = snprintf(NULL, 0, "Q: %s\nA: ", argv[optind]);
        tl_state s;
        exit_if(tl_state_init(&s, &m) == -1, "tl_state_init");
        printf("\nmodel      : %ld parameters, %d layers, %d heads, d=%d, context %d bytes\n",
               m.n_params, m.n_layer, m.n_head, m.d, m.ctx);
        printf("weights    : %zu bytes mapped with mmap (MAP_PRIVATE, PROT_READ)\n", m.map_size);
        printf("KV cache   : %zu bytes per request (+ scratch)\n", s.bytes);
        printf("tokens     : %d of prompt (prefill) + %d generated (decode)\n", prompt_len, steps);
        printf("time       : load %.3f ms, inference %.2f ms (%.0f tokens/s)\n", (t1 - t0) * 1e3,
               (t2 - t1) * 1e3, (prompt_len + steps) / (t2 - t1));
        printf("page faults: %ld during load, %ld during the first inference (minor; major: %ld)\n",
               r1.ru_minflt - r0.ru_minflt, r2.ru_minflt - r1.ru_minflt, r2.ru_majflt - r0.ru_majflt);
        tl_state_free(&s);
    }
    tl_unload(&m);
    return EXIT_SUCCESS;
}
